version: 2
jobs:
  test:
    docker:
      - image: mkusaka/sniffer_dev:latest
    steps:
      - checkout
      - run:
          name: build sninffer
          command: make
      - run:
          name: build notifier
          command: |
              cd notifiers/slack_notifier
              make
      - run:
          name: build log plugin
          command: |
              cd sniffers/log_sniffer
              make

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
